---
abstract: 'IO Interface to compressed data files/buffers'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Compress
no_index:
  directory:
    - t
    - inc
    - t
    - private
requires:
  Compress::Raw::Bzip2: '2.214'
  Compress::Raw::Zlib: '2.214'
  Scalar::Util: '0'
  Encode: '0'
  Time::Local: '0'
resources:
  bugtracker: https://github.com/pmqs/IO-Compress/issues
  homepage: https://github.com/pmqs/IO-Compress
  repository: git://github.com/pmqs/IO-Compress.git
version: '2.214'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
