# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Compress-Base
version:      2.000_09
version_from: lib/IO/Compress/Base.pm
installdirs:  site
requires:
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
