#!/usr/local/bin/perl

use IO::Gunzip qw( $GunzipError );
use strict ;
local ($^W) = 1; #use warnings ;

#die "Usage: gzcat file...\n"
#    unless @ARGV ;

my $file ;
my $buffer ;
my $s;

@ARGV = '-' unless @ARGV ;

foreach $file (@ARGV) {
    
    my $gz = new IO::Gunzip $file
         or die "Cannot open $file: $GunzipError\n" ;

    print $buffer
        while ($s = $gz->read($buffer)) > 0 ;

    die "Error reading from $file: $GunzipError\n" 
        if $s < 0 ;
    
    $gz->close() ;
}

